version: "3.7"
services:
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    ports:
    - 4180:4180
    command:
    - oauth-proxy
    - --provider=oidc
    - --oidc-issuer-url=https://dev-283652.okta.com/oauth2/default
    - --redirect-url=http://localhost:4180/oauth2/callback
    - --client-id=${OAUTH2_PROXY_CLIENT_ID}
    - --client-secret=${OAUTH2_PROXY_CLIENT_SECRET}
    - --email-domain=*
    - --whitelist-domain=localhost
    - --cookie-samesite=lax
    - --cookie-refresh=1h
    - --cookie-expire=4h
    - --set-authorization-header=true
    - --http-address=http://0.0.0.0:4180
    - --upstream=http://web:4567
    - --skip-provider-button=true
    - --cookie-secret=${OAUTH2_PROXY_COOKIE_SECRET}
    - --cookie-name=_oauth2_proxy_local
    - --cookie-secure=false
    - --pass-access-token=true
  web:
    build: .
    ports:
    - 4567:4567
    volumes:
    - .:/code

